#!/usr/bin/env python3
"""Audit the 20k Human Heart Cell Atlas AnnData.

Outputs
-------
results/data_audit.json        full structural + counts audit
results/obs_columns.csv        per-obs-column dtype / cardinality / values
results/donor_celltype_crosstab.csv
results/donor_cell_counts.csv
docs/DATA_DICTIONARY.md        audited key selection (donor/batch/label/counts)

No model is trained here. If raw integer counts cannot be located, the script
exits non-zero (per the no-silent-logcounts rule).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from heartmap.config import load_config  # noqa: E402
from heartmap.data import (audit_adata, check_nuisance_labels_absent,
                           confirm_keys, load_heart_dataset, validate_counts,
                           write_audit_tables)  # noqa: E402
from heartmap.provenance import collect_environment, sha256_file, write_json  # noqa: E402

DATASET_URL = (
    "https://github.com/YosefLab/scVI-data/blob/master/"
    "hca_subsampled_20k.h5ad?raw=true"
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="configs/main.yaml")
    args = parser.parse_args()
    cfg = load_config(args.config)
    root = cfg.root
    results = root / "results"
    results.mkdir(exist_ok=True)
    cfg.data_raw_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading dataset via {cfg['dataset_loader']} ...")
    adata = load_heart_dataset(
        save_path=str(cfg.data_raw_dir),
        remove_nuisance_clusters=bool(cfg["remove_nuisance_clusters"]),
    )
    print(adata)

    audit = audit_adata(adata)
    write_audit_tables(adata, results)

    # ---- Raw-counts verification (hard failure if not counts) -------------
    # This loader ships raw integer UMI counts in adata.X with no layers and
    # no .raw. Prove X is counts, then materialise the explicit 'counts' layer
    # that every downstream stage references via layer='counts'.
    x_info = validate_counts(adata, None)
    audit["counts_validation_X"] = x_info
    if cfg["counts_layer"] not in adata.layers:
        adata.layers[cfg["counts_layer"]] = adata.X.copy()
    counts_info = validate_counts(adata, cfg["counts_layer"])
    audit["counts_validation_configured"] = counts_info
    audit["layers_after_materialisation"] = {
        cfg["counts_layer"]: {
            k: counts_info[k]
            for k in ("type", "dtype", "n_nonzero", "looks_like_integer_counts")
        }
    }

    # ---- Configured keys ---------------------------------------------------
    audit["configured_keys"] = confirm_keys(adata, cfg)
    audit["nuisance_check"] = check_nuisance_labels_absent(
        adata, cfg["cell_type_key"]
    )

    # ---- Donor / cell-type distributions ----------------------------------
    donor_counts = (
        adata.obs[cfg["donor_key"]].value_counts().rename_axis("donor").to_frame("n_cells")
    )
    donor_counts.to_csv(results / "donor_cell_counts.csv")

    crosstab = pd.crosstab(
        adata.obs[cfg["donor_key"]].astype(str),
        adata.obs[cfg["cell_type_key"]].astype(str),
    )
    crosstab.to_csv(results / "donor_celltype_crosstab.csv")

    local_file = cfg.data_raw_dir / "hca_subsampled_20k.h5ad"
    audit["dataset"] = {
        "loader": cfg["dataset_loader"],
        "source_url": DATASET_URL,
        "local_file": str(local_file.relative_to(root)),
        "file_sha256": sha256_file(local_file) if local_file.exists() else None,
        "remove_nuisance_clusters": bool(cfg["remove_nuisance_clusters"]),
    }
    audit["environment"] = {
        k: collect_environment()[k]
        for k in ("python", "scvi", "scanpy", "anndata", "numpy", "torch", "lightning")
    }

    write_json(results / "data_audit.json", audit)
    print("Wrote results/data_audit.json")

    _write_data_dictionary(root / "docs" / "DATA_DICTIONARY.md", adata, audit, cfg)
    print("Wrote docs/DATA_DICTIONARY.md")

    # Final guardrail summary.
    print(
        "Counts confirmed at:",
        counts_info["location"],
        "| integer-like:",
        counts_info["looks_like_integer_counts"],
    )


def _write_data_dictionary(path: Path, adata, audit: dict, cfg) -> None:
    ck = audit["configured_keys"]
    donor_key = cfg["donor_key"]
    batch_key = cfg["batch_key"]
    label_key = cfg["cell_type_key"]
    label_counts = adata.obs[label_key].value_counts()
    donor_counts = adata.obs[donor_key].value_counts()
    obs_cols = pd.read_csv(path.parent.parent / "results" / "obs_columns.csv")

    lines = [
        "# Data dictionary — Human Heart Cell Atlas, 20k subsample",
        "",
        "_Generated by `scripts/audit_data.py`. All statements below are derived",
        "from the loaded AnnData, not from field-name guesses._",
        "",
        "## Source",
        "",
        f"- Loader: `{audit['dataset']['loader']}`",
        f"- Source URL: {audit['dataset']['source_url']}",
        f"- Local file: `{audit['dataset']['local_file']}`",
        f"- SHA256: `{audit['dataset']['file_sha256']}`",
        f"- Loader default `remove_nuisance_clusters="
        f"{audit['dataset']['remove_nuisance_clusters']}` (drops "
        "`doublets` / `NotAssigned` upstream of this pipeline)",
        "",
        "## Dimensions",
        "",
        f"- n_obs: **{audit['n_obs']}**",
        f"- n_vars: **{audit['n_vars']}**",
        f"- obs names unique: {audit['obs_names_unique']}",
        f"- var names unique: {audit['var_names_unique']}",
        "",
        "## Matrix layout",
        "",
        f"- `adata.X`: {audit['X']['type']}, dtype {audit['X']['dtype']}, "
        f"{audit['X']['n_nonzero']:,} non-zeros; non-negative & near-integer: "
        f"**{audit['X']['looks_like_integer_counts']}**",
    ]
    for name, info in audit["layers"].items():
        lines.append(
            f"- layer `{name}`: {info['type']}, dtype {info['dtype']}, "
            f"{info['n_nonzero']:,} non-zeros; non-negative & near-integer: "
            f"**{info['looks_like_integer_counts']}** "
            f"(max sampled round deviation {info['sampled_max_round_deviation']:.2e})"
        )
    lines += [
        f"- `adata.raw` present: {audit['raw_present']}",
        f"- obsm: {list(adata.obsm.keys()) or 'none'}",
        f"- varm: {list(adata.varm.keys()) or 'none'}",
        f"- uns keys: {audit['uns_keys'] or 'none'}",
        "",
        "## Selected analysis keys",
        "",
        f"- **donor_key = `{donor_key}`** "
        f"({ck['donor_key']['n_unique']} unique donors, "
        f"{ck['donor_key']['n_missing']} missing)",
        f"- **batch_key = `{batch_key}`** — each donor is treated as its own "
        "batch. The subsampled atlas aggregates multiple studies/assays but "
        "donor is the biological unit being held out; donor as batch matches "
        "the scvi-tools heart-atlas usage and prevents any same-donor cells "
        "appearing on both sides.",
        f"- **cell_type_key = `{label_key}`** — author-provided biological "
        "annotation (not Leiden cluster IDs). "
        f"{ck['cell_type_key']['n_unique']} classes:",
        "",
    ]
    for label, n in label_counts.items():
        lines.append(f"  - `{label}`: {int(n):,}")
    lines += [
        "",
        f"- **counts_layer = `{cfg['counts_layer']}`** — raw UMI counts "
        f"validated at `{audit['counts_validation_configured']['location']}` "
        f"(non-negative, max sampled deviation from integer "
        f"{audit['counts_validation_configured']['sampled_max_round_deviation']:.2e}). "
        "`adata.X` also holds raw counts in this loader, but the explicit "
        "`counts` layer is passed to scVI via `layer='counts'`.",
        "",
        "### Candidate fields considered but not used",
        "",
        "| candidate | role | why not primary |",
        "|---|---|---|",
        "| Leiden/cluster-style columns | clusters | not biology; author annotation available |",
        "| `sample`/`channel` (if present) | technical replicate | splits within a donor would leak the held-out donor |",
        "",
        "## Donor cell counts",
        "",
        "| donor | n_cells |",
        "|---|---|",
    ]
    for donor, n in donor_counts.items():
        lines.append(f"| {donor} | {int(n):,} |")
    lines += [
        "",
        f"Full donor × cell-type crosstab: "
        "`results/donor_celltype_crosstab.csv`.",
        "",
        "## All `obs` columns",
        "",
        "| column | dtype | n_unique | n_missing |",
        "|---|---|---|---|",
    ]
    for _, r in obs_cols.iterrows():
        lines.append(
            f"| {r['column']} | {r['dtype']} | {r['n_unique']} | {r['n_missing']} |"
        )
    lines += [
        "",
        "## Annotation hierarchy note",
        "",
        "This subsampled object provides one author-curated cell-type annotation.",
        "The main experiment uses it as a broad-type label. Any finer cell-state",
        "analysis is out of scope and listed as future work.",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
