#!/usr/bin/env python3
"""Read-only environment audit.

Writes docs/environment_audit.md and results/environment.json. This script
installs nothing and trains nothing.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from heartmap.provenance import collect_environment  # noqa: E402


def _sysctl(key: str) -> str | None:
    if sys.platform != "darwin":
        return None
    try:
        out = subprocess.run(
            ["sysctl", "-n", key], capture_output=True, text=True, timeout=10
        )
        return out.stdout.strip() if out.returncode == 0 else None
    except OSError:
        return None


def _which(name: str) -> str | None:
    return shutil.which(name)


def _git_status(repo: Path) -> dict:
    def run(args):
        try:
            out = subprocess.run(
                ["git", *args], cwd=repo, capture_output=True, text=True, timeout=15
            )
            return out.stdout.strip() if out.returncode == 0 else None
        except OSError:
            return None

    return {
        "is_repo": run(["rev-parse", "--is-inside-work-tree"]) == "true",
        "commit": run(["rev-parse", "HEAD"]),
        "uncommitted": (run(["status", "--porcelain"]) or "").splitlines()
        if run(["rev-parse", "--is-inside-work-tree"]) == "true"
        else [],
    }


def collect() -> dict:
    env = collect_environment()
    mem_bytes = _sysctl("hw.memsize")
    disk = shutil.disk_usage(Path.cwd())
    cpu_brand = _sysctl("machdep.cpu.brand_string")
    env.update(
        {
            "cpu_brand": cpu_brand,
            "cpu_count_logical": os.cpu_count(),
            "memory_total_bytes": int(mem_bytes) if mem_bytes else None,
            "disk_total_bytes": disk.total,
            "disk_free_bytes": disk.free,
            "conda": _which("conda"),
            "mamba": _which("mamba"),
            "git_path": _which("git"),
            "python_executable": sys.executable,
            "git_status": _git_status(Path.cwd()),
        }
    )
    # Network reachability (best effort, short timeouts).
    import urllib.request

    for name, url in {
        "scvi_docs": "https://docs.scvi-tools.org/en/stable/",
        "pypi": "https://pypi.org/simple/",
        "github": "https://github.com",
        "heart_data": (
            "https://raw.githubusercontent.com/YosefLab/scVI-data/master/"
            "hca_subsampled_20k.h5ad"
        ),
    }.items():
        try:
            req = urllib.request.Request(url, method="HEAD")
            with urllib.request.urlopen(req, timeout=10) as resp:
                env.setdefault("network", {})[name] = resp.status
        except Exception as exc:  # noqa: BLE001
            env.setdefault("network", {})[name] = f"unreachable: {type(exc).__name__}"
    return env


def render_markdown(env: dict) -> str:
    gpu = env["gpus"][0]["name"] if env["gpus"] else "None detected"
    lines = [
        "# Environment audit",
        "",
        "_Generated by `scripts/check_environment.py` (read-only)._",
        "",
        f"- Timestamp (UTC): {env['timestamp_utc']}",
        f"- Operating system: {env['platform']}",
        f"- CPU: {env.get('cpu_brand') or 'unknown'} "
        f"({env.get('cpu_count_logical')} logical cores)",
        f"- Memory: "
        f"{(env.get('memory_total_bytes') or 0) / 1e9:.1f} GB",
        f"- Disk (cwd): {env['disk_free_bytes'] / 1e9:.1f} GB free of "
        f"{env['disk_total_bytes'] / 1e9:.1f} GB",
        f"- Python: {env['python']} ({env['python_executable']})",
        f"- conda: {env.get('conda') or 'not found'}",
        f"- mamba: {env.get('mamba') or 'not found'}",
        f"- git: {env.get('git_path') or 'not found'}",
        "",
        "## Scientific stack",
        "",
        f"- scvi-tools: {env.get('scvi') or 'NOT INSTALLED'}",
        f"- scanpy: {env.get('scanpy') or 'not installed'}",
        f"- anndata: {env.get('anndata')}",
        f"- scikit-learn: {env.get('sklearn')}",
        f"- pandas: {env.get('pandas')}",
        f"- numpy: {env.get('numpy')}",
        f"- scipy: {env.get('scipy')}",
        f"- PyTorch: {env.get('torch')}",
        f"- PyTorch Lightning: {env.get('lightning')}",
        "",
        "## Accelerators",
        "",
        f"- CUDA available: **{env['cuda_available']}**",
        f"- CUDA version: {env.get('cuda_version')}",
        f"- NVIDIA GPU: {gpu}",
        f"- Apple MPS reported available: {env['mps_available']}",
        "- MPS is **not** used automatically by this project: scvi-tools / "
        "PyTorch Lightning do not provide reliable, officially documented MPS "
        "support for this workflow. Local training therefore runs on CPU; "
        "GPU runs use Google Colab (CUDA).",
        "",
        "## Git",
        "",
        f"- Is git repo: {env['git_status']['is_repo']}",
        f"- HEAD: {env['git_status'].get('commit')}",
        f"- Uncommitted entries: {len(env['git_status']['uncommitted'])}",
        "",
        "## Network reachability",
        "",
    ]
    for name, status in env.get("network", {}).items():
        lines.append(f"- {name}: {status}")
    lines += [
        "",
        "## Execution backend decision",
        "",
        "Backend **B** from the project brief: local CPU (Intel, no CUDA). "
        "Data audit, leakage tests, PCA+kNN baseline and CPU smoke experiments "
        "run locally; full SCVI/SCANVI/scArches training is provided both as "
        "CPU-capable scripts and as a Google Colab notebook (CUDA).",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-md", default="docs/environment_audit.md")
    parser.add_argument("--out-json", default="results/environment.json")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    env = collect()
    (root / args.out_md).parent.mkdir(parents=True, exist_ok=True)
    (root / args.out_md).write_text(render_markdown(env))
    (root / args.out_json).parent.mkdir(parents=True, exist_ok=True)
    (root / args.out_json).write_text(json.dumps(env, indent=2, default=str))
    print(json.dumps(
        {
            "python": env["python"],
            "scvi": env.get("scvi"),
            "cuda": env["cuda_available"],
            "mps": env["mps_available"],
        },
        indent=2,
    ))
    print(f"Wrote {args.out_md} and {args.out_json}")


if __name__ == "__main__":
    main()
